-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME 
FROM ANIMAL_INS AS I
LEFT OUTER JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY I.DATETIME
LIMIT 3;