-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_ID, PRODUCT.PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRODUCT
JOIN FOOD_ORDER AS ORDERS
ON PRODUCT.PRODUCT_ID = ORDERS.PRODUCT_ID
WHERE ORDERS.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT.PRODUCT_ID ASC;